attributes_listA_small = [
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R141 savings per 100 km <br> (R130 + R11 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R202 savings per 100 km <br> (R160 + R42 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R156 savings per 100 km <br> (R145 + R11 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R172 savings per 100 km <br> (R130 + R42 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R187 savings per 100 km <br> (R145 + R42 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R171 savings per 100 km <br> (R160 + R11 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R156 savings per 100 km <br> (R145 + R11 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R202 savings per 100 km <br> (R160 + R42 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R171 savings per 100 km <br> (R160 + R11 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R172 savings per 100 km <br> (R130 + R42 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R141 savings per 100 km <br> (R130 + R11 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R187 savings per 100 km <br> (R145 + R42 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R187 savings per 100 km <br> (R145 + R42 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R141 savings per 100 km <br> (R130 + R11 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R202 savings per 100 km <br> (R160 + R42 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R156 savings per 100 km <br> (R145 + R11 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R171 savings per 100 km <br> (R160 + R11 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R172 savings per 100 km <br> (R130 + R42 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listA_medium = [
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R161 savings per 100 km <br> (R150 + R11 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R222 savings per 100 km <br> (R180 + R42 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R176 savings per 100 km <br> (R165 + R11 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R192 savings per 100 km <br> (R150 + R42 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R207 savings per 100 km <br> (R165 + R42 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R191 savings per 100 km <br> (R180 + R11 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R176 savings per 100 km <br> (R165 + R11 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R222 savings per 100 km <br> (R180 + R42 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R191 savings per 100 km <br> (R180 + R11 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R192 savings per 100 km <br> (R150 + R42 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R161 savings per 100 km <br> (R150 + R11 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R207 savings per 100 km <br> (R165 + R42 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R207 savings per 100 km <br> (R165 + R42 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R161 savings per 100 km <br> (R150 + R11 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R222 savings per 100 km <br> (R180 + R42 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R176 savings per 100 km <br> (R165 + R11 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R191 savings per 100 km <br> (R180 + R11 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R192 savings per 100 km <br> (R150 + R42 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listA_large = [
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R186 savings per 100 km <br> (R175 + R11 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R257 savings per 100 km <br> (R215 + R42 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R206 savings per 100 km <br> (R195 + R11 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R217 savings per 100 km <br> (R175 + R42 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R237 savings per 100 km <br> (R195 + R42 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R226 savings per 100 km <br> (R215 + R11 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R206 savings per 100 km <br> (R195 + R11 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R257 savings per 100 km <br> (R215 + R42 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R226 savings per 100 km <br> (R215 + R11 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R217 savings per 100 km <br> (R175 + R42 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R186 savings per 100 km <br> (R175 + R11 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R237 savings per 100 km <br> (R195 + R42 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R237 savings per 100 km <br> (R195 + R42 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R186 savings per 100 km <br> (R175 + R11 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R257 savings per 100 km <br> (R215 + R42 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R206 savings per 100 km <br> (R195 + R11 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R226 savings per 100 km <br> (R215 + R11 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R217 savings per 100 km <br> (R175 + R42 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_small = [
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R141 savings per 100 km <br> (R130 + R11 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R202 savings per 100 km <br> (R160 + R42 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R156 savings per 100 km <br> (R145 + R11 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R172 savings per 100 km <br> (R130 + R42 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R187 savings per 100 km <br> (R145 + R42 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R171 savings per 100 km <br> (R160 + R11 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R156 savings per 100 km <br> (R145 + R11 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R202 savings per 100 km <br> (R160 + R42 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R171 savings per 100 km <br> (R160 + R11 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R172 savings per 100 km <br> (R130 + R42 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R141 savings per 100 km <br> (R130 + R11 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R187 savings per 100 km <br> (R145 + R42 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R187 savings per 100 km <br> (R145 + R42 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R141 savings per 100 km <br> (R130 + R11 due to fuel tax)",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R202 savings per 100 km <br> (R160 + R42 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R156 savings per 100 km <br> (R145 + R11 due to fuel tax)",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R171 savings per 100 km <br> (R160 + R11 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R172 savings per 100 km <br> (R130 + R42 due to fuel tax)",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_medium = [
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R161 savings per 100 km <br> (R150 + R11 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R222 savings per 100 km <br> (R180 + R42 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R176 savings per 100 km <br> (R165 + R11 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R192 savings per 100 km <br> (R150 + R42 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R207 savings per 100 km <br> (R165 + R42 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R191 savings per 100 km <br> (R180 + R11 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R176 savings per 100 km <br> (R165 + R11 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R222 savings per 100 km <br> (R180 + R42 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R191 savings per 100 km <br> (R180 + R11 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R192 savings per 100 km <br> (R150 + R42 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R161 savings per 100 km <br> (R150 + R11 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R207 savings per 100 km <br> (R165 + R42 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R207 savings per 100 km <br> (R165 + R42 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R161 savings per 100 km <br> (R150 + R11 due to fuel tax)",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R222 savings per 100 km <br> (R180 + R42 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R176 savings per 100 km <br> (R165 + R11 due to fuel tax)",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R191 savings per 100 km <br> (R180 + R11 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R192 savings per 100 km <br> (R150 + R42 due to fuel tax)",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_large = [
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R186 savings per 100 km <br> (R175 + R11 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R257 savings per 100 km <br> (R215 + R42 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R206 savings per 100 km <br> (R195 + R11 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R217 savings per 100 km <br> (R175 + R42 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R237 savings per 100 km <br> (R195 + R42 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R226 savings per 100 km <br> (R215 + R11 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R206 savings per 100 km <br> (R195 + R11 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R257 savings per 100 km <br> (R215 + R42 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R226 savings per 100 km <br> (R215 + R11 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R217 savings per 100 km <br> (R175 + R42 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R186 savings per 100 km <br> (R175 + R11 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R237 savings per 100 km <br> (R195 + R42 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R237 savings per 100 km <br> (R195 + R42 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R186 savings per 100 km <br> (R175 + R11 due to fuel tax)",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R257 savings per 100 km <br> (R215 + R42 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R206 savings per 100 km <br> (R195 + R11 due to fuel tax)",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R226 savings per 100 km <br> (R215 + R11 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R217 savings per 100 km <br> (R175 + R42 due to fuel tax)",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_small = [
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_medium = [
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_large = [
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_small = [
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "240 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R112,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 km",
        "Battery Range": "420 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R161,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 km",
        "Battery Range": "600 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_medium = [
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "300 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R189,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 km",
        "Battery Range": "480 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R252,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 km",
        "Battery Range": "660 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_large = [
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R686,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "370 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "35% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R497,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 km",
        "Battery Range": "550 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "R581,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 km",
        "Battery Range": "730 km on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listE = [
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R35,000 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R35,000 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R17,500 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R17,500 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R35,000 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R17,500 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R17,500 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R35,000 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R17,500 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R35,000 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R17,500 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R35,000 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
]
