attributes_listA_small = [
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]

attributes_listA_medium = [
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]

attributes_listA_large = [
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listB_small = [
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£15 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listB_medium = [
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listB_large = [
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£18 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listC_small = [
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listC_medium = [
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listC_large = [
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listD_small = [
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "140 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£8,400",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "380 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listD_medium = [
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "180 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£14,700",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£23,000",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "420 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listD_large = [
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£70,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "220 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£49,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "£59,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "460 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listE = [
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£5,200 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£5,200 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£2,600 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£2,600 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£5,200 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£2,600 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£2,600 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£5,200 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£2,600 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£5,200 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£2,600 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£5,200 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
]
