attributes_listA_small = [
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.2 savings per 100 miles <br> ($6.7 + $1.5 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$14.1 savings per 100 miles <br> ($8.1 + $6 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.9 savings per 100 miles <br> ($7.4 + $1.5 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$12.7 savings per 100 miles <br> ($6.7 + $6 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$13.4 savings per 100 miles <br> ($7.4 + $6 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles <br> ($8.1 + $1.5 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.9 savings per 100 miles <br> ($7.4 + $1.5 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$14.1 savings per 100 miles <br> ($8.1 + $6 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles <br> ($8.1 + $1.5 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$12.7 savings per 100 miles <br> ($6.7 + $6 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.2 savings per 100 miles <br> ($6.7 + $1.5 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$13.4 savings per 100 miles <br> ($7.4 + $6 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$13.4 savings per 100 miles <br> ($7.4 + $6 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$8.2 savings per 100 miles <br> ($6.7 + $1.5 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$14.1 savings per 100 miles <br> ($8.1 + $6 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.9 savings per 100 miles <br> ($7.4 + $1.5 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles <br> ($8.1 + $1.5 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$12.7 savings per 100 miles <br> ($6.7 + $6 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listA_medium = [
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles <br> ($7.2 + $1.5 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$14.8 savings per 100 miles <br> ($8.8 + $6 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$9.5 savings per 100 miles <br> ($8 + $1.5 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$13.2 savings per 100 miles <br> ($7.2 + $6 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$14 savings per 100 miles <br> ($8 + $6 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$10.3 savings per 100 miles <br> ($8.8 + $1.5 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$9.5 savings per 100 miles <br> ($8 + $1.5 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$14.8 savings per 100 miles <br> ($8.8 + $6 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$10.3 savings per 100 miles <br> ($8.8 + $1.5 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$13.2 savings per 100 miles <br> ($7.2 + $6 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles <br> ($7.2 + $1.5 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$14 savings per 100 miles <br> ($8 + $6 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$14 savings per 100 miles <br> ($8 + $6 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles <br> ($7.2 + $1.5 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$14.8 savings per 100 miles <br> ($8.8 + $6 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$9.5 savings per 100 miles <br> ($8 + $1.5 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$10.3 savings per 100 miles <br> ($8.8 + $1.5 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$13.2 savings per 100 miles <br> ($7.2 + $6 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listA_large = [
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.2 savings per 100 miles <br> ($8.7 + $1.5 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$16.5 savings per 100 miles <br> ($10.5 + $6 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$11.1 savings per 100 miles <br> ($9.6 + $1.5 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$14.7 savings per 100 miles <br> ($8.7 + $6 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$15.6 savings per 100 miles <br> ($9.6 + $6 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$12.0 savings per 100 miles <br> ($10.5 + $1.5 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$11.1 savings per 100 miles <br> ($9.6 + $1.5 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$16.5 savings per 100 miles <br> ($10.5 + $6 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$12.0 savings per 100 miles <br> ($10.5 + $1.5 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$14.7 savings per 100 miles <br> ($8.7 + $6 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.2 savings per 100 miles <br> ($8.7 + $1.5 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$15.6 savings per 100 miles <br> ($9.6 + $6 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$15.6 savings per 100 miles <br> ($9.6 + $6 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$10.2 savings per 100 miles <br> ($8.7 + $1.5 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$16.5 savings per 100 miles <br> ($10.5 + $6 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$11.1 savings per 100 miles <br> ($9.6 + $1.5 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$12.0 savings per 100 miles <br> ($10.5 + $1.5 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$14.7 savings per 100 miles <br> ($8.7 + $6 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_small = [
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.2 savings per 100 miles <br> ($6.7 + $1.5 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$14.1 savings per 100 miles <br> ($8.1 + $6 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.9 savings per 100 miles <br> ($7.4 + $1.5 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$12.7 savings per 100 miles <br> ($6.7 + $6 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$13.4 savings per 100 miles <br> ($7.4 + $6 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles <br> ($8.1 + $1.5 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.9 savings per 100 miles <br> ($7.4 + $1.5 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$14.1 savings per 100 miles <br> ($8.1 + $6 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles <br> ($8.1 + $1.5 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$12.7 savings per 100 miles <br> ($6.7 + $6 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.2 savings per 100 miles <br> ($6.7 + $1.5 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$13.4 savings per 100 miles <br> ($7.4 + $6 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$13.4 savings per 100 miles <br> ($7.4 + $6 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$8.2 savings per 100 miles <br> ($6.7 + $1.5 due to gasoline tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$14.1 savings per 100 miles <br> ($8.1 + $6 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.9 savings per 100 miles <br> ($7.4 + $1.5 due to gasoline tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles <br> ($8.1 + $1.5 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$12.7 savings per 100 miles <br> ($6.7 + $6 due to gasoline tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_medium = [
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles <br> ($7.2 + $1.5 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$14.8 savings per 100 miles <br> ($8.8 + $6 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$9.5 savings per 100 miles <br> ($8 + $1.5 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$13.2 savings per 100 miles <br> ($7.2 + $6 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$14 savings per 100 miles <br> ($8 + $6 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$10.3 savings per 100 miles <br> ($8.8 + $1.5 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$9.5 savings per 100 miles <br> ($8 + $1.5 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$14.8 savings per 100 miles <br> ($8.8 + $6 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$10.3 savings per 100 miles <br> ($8.8 + $1.5 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$13.2 savings per 100 miles <br> ($7.2 + $6 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles <br> ($7.2 + $1.5 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$14 savings per 100 miles <br> ($8 + $6 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$14 savings per 100 miles <br> ($8 + $6 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles <br> ($7.2 + $1.5 due to gasoline tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$14.8 savings per 100 miles <br> ($8.8 + $6 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$9.5 savings per 100 miles <br> ($8 + $1.5 due to gasoline tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$10.3 savings per 100 miles <br> ($8.8 + $1.5 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$13.2 savings per 100 miles <br> ($7.2 + $6 due to gasoline tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_large = [
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.2 savings per 100 miles <br> ($8.7 + $1.5 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$16.5 savings per 100 miles <br> ($10.5 + $6 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$11.1 savings per 100 miles <br> ($9.6 + $1.5 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$14.7 savings per 100 miles <br> ($8.7 + $6 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$15.6 savings per 100 miles <br> ($9.6 + $6 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$12.0 savings per 100 miles <br> ($10.5 + $1.5 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$11.1 savings per 100 miles <br> ($9.6 + $1.5 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$16.5 savings per 100 miles <br> ($10.5 + $6 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$12.0 savings per 100 miles <br> ($10.5 + $1.5 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$14.7 savings per 100 miles <br> ($8.7 + $6 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.2 savings per 100 miles <br> ($8.7 + $1.5 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$15.6 savings per 100 miles <br> ($9.6 + $6 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$15.6 savings per 100 miles <br> ($9.6 + $6 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$10.2 savings per 100 miles <br> ($8.7 + $1.5 due to gasoline tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$16.5 savings per 100 miles <br> ($10.5 + $6 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$11.1 savings per 100 miles <br> ($9.6 + $1.5 due to gasoline tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$12.0 savings per 100 miles <br> ($10.5 + $1.5 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$14.7 savings per 100 miles <br> ($8.7 + $6 due to gasoline tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_small = [
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_medium = [
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_large = [
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "11 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_small = [
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$30,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$16,000",
        "Savings Compared to Gasoline Car": "$7.4 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$8.1 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$23,000",
        "Savings Compared to Gasoline Car": "$6.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_medium = [
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$45,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$27,000",
        "Savings Compared to Gasoline Car": "$8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$8.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$36,000",
        "Savings Compared to Gasoline Car": "$7.2 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_large = [
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$98,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "60% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$71,000",
        "Savings Compared to Gasoline Car": "$9.6 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$10.6 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "70% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "$83,000",
        "Savings Compared to Gasoline Car": "$8.7 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50% of emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listE = [
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighborhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 50% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighborhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 20% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighborhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 50% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighborhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighborhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 20% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighborhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 20% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 50% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 20% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 50% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 20% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 50% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 20% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 50% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "83% who bought a new car chose an EV last year",
    },
]

