attributes_listA_small = [
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.0 savings per 100 miles <br> (£9.9 + £1.1 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.9 savings per 100 miles <br> (£10.8 + £1.1 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£15.0 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles <br> (£11.7 + £1.1 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.9 savings per 100 miles <br> (£10.8 + £1.1 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles <br> (£11.7 + £1.1 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.0 savings per 100 miles <br> (£9.9 + £1.1 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£15.0 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£15.0 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£11.0 savings per 100 miles <br> (£9.9 + £1.1 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.9 savings per 100 miles <br> (£10.8 + £1.1 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles <br> (£11.7 + £1.1 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listA_medium = [
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.6 savings per 100 miles <br> (£11.5 + £1.1 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£13.9 savings per 100 miles <br> (£12.8 + £1.1 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£17.0 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£15.2 savings per 100 miles <br> (£14.1 + £1.1 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£13.9 savings per 100 miles <br> (£12.8 + £1.1 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£15.2 savings per 100 miles <br> (£14.1 + £1.1 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.6 savings per 100 miles <br> (£11.5 + £1.1 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£17.0 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£17.0 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£12.6 savings per 100 miles <br> (£11.5 + £1.1 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£13.9 savings per 100 miles <br> (£12.8 + £1.1 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£15.2 savings per 100 miles <br> (£14.1 + £1.1 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listA_large = [
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£14.9 savings per 100 miles <br> (£13.8 + £1.1 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£16.5 savings per 100 miles <br> (£15.4 + £1.1 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£18.0 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£18.1 savings per 100 miles <br> (£17 + £1.1 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£16.5 savings per 100 miles <br> (£15.4 + £1.1 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£18.1 savings per 100 miles <br> (£17 + £1.1 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£18.0 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£14.9 savings per 100 miles <br> (£13.8 + £1.1 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£14.9 savings per 100 miles <br> (£13.8 + £1.1 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£16.5 savings per 100 miles <br> (£15.4 + £1.1 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£18.1 savings per 100 miles <br> (£17 + £1.1 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£18.0 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_small = [
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.0 savings per 100 miles <br> (£9.9 + £1.1 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.9 savings per 100 miles <br> (£10.8 + £1.1 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£15.0 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles <br> (£11.7 + £1.1 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.9 savings per 100 miles <br> (£10.8 + £1.1 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles <br> (£11.7 + £1.1 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.0 savings per 100 miles <br> (£9.9 + £1.1 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£15.0 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£15.0 savings per 100 miles <br> (£10.8 + £4.2 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£11.0 savings per 100 miles <br> (£9.9 + £1.1 due to fuel tax)",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£15.9 savings per 100 miles <br> (£11.7 + £4.2 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.9 savings per 100 miles <br> (£10.8 + £1.1 due to fuel tax)",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles <br> (£11.7 + £1.1 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles <br> (£9.9 + £4.2 due to fuel tax)",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_medium = [
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.6 savings per 100 miles <br> (£11.5 + £1.1 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£13.9 savings per 100 miles <br> (£12.8 + £1.1 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£17.0 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£15.2 savings per 100 miles <br> (£14.1 + £1.1 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£13.9 savings per 100 miles <br> (£12.8 + £1.1 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£15.2 savings per 100 miles <br> (£14.1 + £1.1 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.6 savings per 100 miles <br> (£11.5 + £1.1 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£17.0 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£17.0 savings per 100 miles <br> (£12.8 + £4.2 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£12.6 savings per 100 miles <br> (£11.5 + £1.1 due to fuel tax)",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£18.3 savings per 100 miles <br> (£14.1 + £4.2 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£13.9 savings per 100 miles <br> (£12.8 + £1.1 due to fuel tax)",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£15.2 savings per 100 miles <br> (£14.1 + £1.1 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£15.7 savings per 100 miles <br> (£11.5 + £4.2 due to fuel tax)",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listB_large = [
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£14.9 savings per 100 miles <br> (£13.8 + £1.1 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£16.5 savings per 100 miles <br> (£15.4 + £1.1 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£18.0 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£18.1 savings per 100 miles <br> (£17 + £1.1 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£16.5 savings per 100 miles <br> (£15.4 + £1.1 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£18.1 savings per 100 miles <br> (£17 + £1.1 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£18.0 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£14.9 savings per 100 miles <br> (£13.8 + £1.1 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£19.6 savings per 100 miles <br> (£15.4 + £4.2 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£14.9 savings per 100 miles <br> (£13.8 + £1.1 due to fuel tax)",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£21.2 savings per 100 miles <br> (£17 + £4.2 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£16.5 savings per 100 miles <br> (£15.4 + £1.1 due to fuel tax)",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£18.1 savings per 100 miles <br> (£17 + £1.1 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£18.0 savings per 100 miles <br> (£13.8 + £4.2 due to fuel tax)",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_small = [
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_medium = [
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listC_large = [
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "19 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "13 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_small = [
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£21,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "150 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£11,200",
        "Savings Compared to Petrol Car": "£10.8 savings per 100 miles",
        "Battery Range": "260 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£11.7 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£16,000",
        "Savings Compared to Petrol Car": "£9.9 savings per 100 miles",
        "Battery Range": "370 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_medium = [
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£31,500",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "190 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£18,900",
        "Savings Compared to Petrol Car": "£12.8 savings per 100 miles",
        "Battery Range": "300 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£14.1 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£25,200",
        "Savings Compared to Petrol Car": "£11.5 savings per 100 miles",
        "Battery Range": "410 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listD_large = [
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£68,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "230 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£49,700",
        "Savings Compared to Petrol Car": "£15.4 savings per 100 miles",
        "Battery Range": "340 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£17 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
    {
        "Purchase Price": "£58,000",
        "Savings Compared to Petrol Car": "£13.8 savings per 100 miles",
        "Battery Range": "450 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbors drive a similar electric car",
    },
]

attributes_listE = [
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£5200 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£5200 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£2600 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£2600 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£5200 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£2600 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£2600 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£5200 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£2600 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "£5200 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£40 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "£2600 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "£160 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "£5200 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
]

