attributes_listA_small = [
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]

attributes_listA_medium = [
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]

attributes_listA_large = [
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listB_small = [
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R185 savings per 100 kilometers <br> (R145 + R40 due to fuel tax)",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R200 savings per 100 kilometers <br> (R160 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R170 savings per 100 kilometers <br> (R130 + R40 due to fuel tax)",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listB_medium = [
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R105 savings per 100 kilometers <br> (R165 + R40 due to fuel tax)",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R220 savings per 100 kilometers <br> (R180 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R190 savings per 100 kilometers <br> (R150 + R40 due to fuel tax)",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listB_large = [
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R235 savings per 100 kilometers <br> (R195 + R40 due to fuel tax)",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R255 savings per 100 kilometers <br> (R215 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers <br> (R175 + R40 due to fuel tax)",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listC_small = [
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listC_medium = [
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listC_large = [
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "40 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "15 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "50 metric tons of emissions",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listD_small = [
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R210,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "220 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R84,000",
        "Savings Compared to Petrol Car": "R145 savings per 100 kilometers",
        "Battery Range": "410 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R160 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R130 savings per 100 kilometers",
        "Battery Range": "600 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listD_medium = [
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R315,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "290 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R147,000",
        "Savings Compared to Petrol Car": "R165 savings per 100 kilometers",
        "Battery Range": "480 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R180 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R231,000",
        "Savings Compared to Petrol Car": "R150 savings per 100 kilometers",
        "Battery Range": "670 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listD_large = [
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "8% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "40% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R700,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "360 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "30% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R490,000",
        "Savings Compared to Petrol Car": "R195 savings per 100 kilometers",
        "Battery Range": "550 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R215 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
    {
        "Investment Costs": "R595,000",
        "Savings Compared to Petrol Car": "R175 savings per 100 kilometers",
        "Battery Range": "740 kilometers on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "25% of emissions saved compared to petrol car",
        "Drivers in the Neighbourhood": "72% of neighbours drive a similar electric car",
    },
]
attributes_listE = [
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R52,000 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R52,000 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R26,000 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R26,000 price reduction",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No climate label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R52,000 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R26,000 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R26,000 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R52,000 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R26,000 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "11% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "No new tax on road fuel",
        "Subsidy on EV Price": "R52,000 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "47% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R400 per tCO2: about 20% fuel price increase",
        "Subsidy on EV Price": "R26,000 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
    {
        "Carbon Tax on Fuel": "R1600 per tCO2: about 50% fuel price increase",
        "Subsidy on EV Price": "R52,000 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighbourhood": "83% who bought a new car chose an EV last year",
    },
]
