attributes_listA_small = [
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $1.5 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listA_medium = [
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listA_large = [
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $1.5 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listB_small = [
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $1.5 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listB_medium = [
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listB_large = [
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $6 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $1.5 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $3 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $1.5 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $3 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 + $6 carbon tax savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $3 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 + $1.5 carbon tax savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 + $6 carbon tax savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listC_small = [
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listC_medium = [
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listC_large = [
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "7 metric tons of emissions",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "12 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "20 metric tons of emissions",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listD_small = [
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.3 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$18,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$30,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $4.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$6,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listD_medium = [
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $5.5 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$36,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$24,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$48,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.7 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listD_large = [
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "45% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "3% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "24% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $6.4 savings",
        "Battery Range": "120 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$82,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "55% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$70,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $7.6 savings",
        "Battery Range": "280 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
    {
        "Investment Costs": "$94,000",
        "Savings Compared to Gasoline Car": "Per 100 miles: $9.2 savings",
        "Battery Range": "440 miles on a single charge",
        "Lifecycle Greenhouse Gas Emissions": "65% emissions saved compared to gasoline car",
        "Drivers in the Neighborhood": "67% of neighbors drive a similar electric car",
    },
]

attributes_listE = [
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "30% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 45% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "8% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 45% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "8% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 15% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "No label",
        "Drivers in the Neighborhood": "81% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 15% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "30% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 45% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "81% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "30% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 45% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "8% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 15% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "No label",
        "Drivers in the Neighborhood": "30% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No label",
        "Drivers in the Neighborhood": "81% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 15% gas price increase",
        "Subsidy on EV Price": "No subsidy",
        "Climate Label on Cars": "No label",
        "Drivers in the Neighborhood": "81% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 45% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "81% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "8% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$240 per tCO2: about 45% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "No label",
        "Drivers in the Neighborhood": "8% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 15% gas price increase",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Voluntary manufacturer label",
        "Drivers in the Neighborhood": "8% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "30% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "No new tax on gasoline",
        "Subsidy on EV Price": "$7500 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "30% who bought a new car chose an EV last year"
    },
    {
        "Carbon Tax on Gasoline": "$60 per tCO2: about 15% gas price increase",
        "Subsidy on EV Price": "$3750 price reduction",
        "Climate Label on Cars": "Mandatory manufacturer label",
        "Drivers in the Neighborhood": "30% who bought a new car chose an EV last year"}
]