class Lexicon:
    # General
    next = "Siguiente"
    yes = "Sí"
    no = "No"
    button_start = "Iniciar Tarea"

    # instruction_product = NA
    product_intro_title = "Por favor, lee atentamente: Instrucciones sobre la tarea de elegir un coche"
    product_intro_text1 = "En las próximas páginas, se te presentarán varios escenarios hipotéticos. <b>Imagina que quieres comprar un coche nuevo.</b><br><br>"
    product_intro_text2 = "Tu papel es evaluar diferentes ofertas de <b>vehículos eléctricos</b> y decidir si elegirías comprar cada coche o no. Un coche eléctrico funciona exclusivamente con electricidad, utilizando un motor eléctrico en lugar del motor de combustión interna convencional que se encuentra en los coches típicos.<br><br>"
    product_intro_text3 = "Considera los siguientes atributos que varían según las ofertas:"

    investment_cost = "Costos de Inversión:"
    savings = "Ahorro en Comparación con un Coche de Gasolina"
    emissions = "Emisiones en el Ciclo de Vida:"
    range = "Autonomía de la batería:"
    adopters = "Adoptantes en el vecindario:"

    investment_cost_text = "Este atributo financiero define el <b>precio neto del coche eléctrico</b> en pesos. Existen subvenciones gubernamentales que pueden reducir el precio. El costo depende de la marca del coche y de las subvenciones/descuentos restados."
    savings_text = "Cargar un vehículo eléctrico es <b>más barato que llenar de combustible un coche de gasolina</b>. Por tanto, los costos por kilómetro son menores para los vehículos eléctricos que para los coches de gasolina. El ahorro se calcula comparando los precios de la electricidad con los de la gasolina y la eficiencia de los vehículos eléctricos con la de los coches tradicionales. <b>El valor presentado te indica cuánto pesos puedes ahorrar con este coche eléctrico durante 100 kilómetros.</b>"
    emissions_text = "Las emisiones muestran la huella medioambiental del coche eléctrico <b>en toneladas métricas</b> desde la producción hasta su desmantelamiento tras <b>aprox. 200,000 kilómetros</b>. Esto incluye las emisiones de la producción, la eliminación y la electricidad necesaria para la conducción."
    range_text = "La autonomía de la batería indica la <b>distancia que puede recorrer un vehículo eléctrico con una sola carga de batería</b>. Indica cuántos kilómetros puedes recorrer antes de tener que parar a cargar la batería."
    adopters_text = "Este atributo representa el <b>porcentaje de personas de tu localidad que actualmente conducen un <i>coche eléctrico</i> similar</b>."
    product_intro_text4 = "Cada coche eléctrico presentado en una oferta está diseñado para ajustarse a las características de un coche que considerarías comprar. Esto incluye factores como el modelo, el tamaño, la potencia del motor y el número de puertas."
    product_intro_text5 = "Al igual que en la práctica, los atributos de los productos estarán ocultos detrás de recuadros. Para ver los atributos, pasa el puntero del ratón por encima del recuadro. El recuadro se abrirá, permitiéndote ver la información."
    product_intro_text6 = "Por favor, decide si comprarías o no cada vehículo eléctrico presentado, teniendo en cuenta que necesitas un coche nuevo. "

    # instruction_policy
    policy_intro_title = "Por favor, lee atentamente: Instrucciones sobre la tarea de políticas"
    policy_intro_text1 = "En las páginas siguientes, te presentaremos una serie de paquetes de políticas hipotéticas. Las políticas están diseñadas para fomentar la adopción de vehículos eléctricos. Un coche eléctrico funciona exclusivamente con electricidad, utilizando un motor eléctrico en lugar del motor de combustión interna convencional que se encuentra en los coches típicos."
    policy_intro_text2 = "Tu tarea consiste en evaluar y expresar tu apoyo o rechazo a cada propuesta política."
    policy_intro_text3 = "Cada paquete de políticas constará de diferentes combinaciones de los siguientes atributos:"

    tax = "Impuesto sobre el Carbono de la Gasolina:"
    subsidy = "Subvenciones a los costos de Inversión:"
    label = "Etiqueta Climática:"

    tax_text = "El paquete de políticas puede incluir un <b>impuesto sobre las emisiones de carbono de la gasolina</b>. Este impuesto se expresa en pesos por tonelada métrica de CO2. Cada litro de gasolina quemado produce unos 2.5 kilogramos de CO2, por lo que el impuesto sobre el carbono aumentaría el precio del combustible. Como resultado, el ahorro por conducir un vehículo eléctrico sería mayor en comparación con un coche de gasolina. Los ingresos fiscales se redistribuirían entre los hogares con bajos ingresos, de modo que quienes no pueden permitirse un vehículo eléctrico pero tienen que depender de su coche no se vean perjudicados."
    subsidy_text = "Este atributo indica si existen <b>subvenciones gubernamentales (descuentos en el precio)</b> proporcionadas a los particulares que compran un vehículo eléctrico. Las subvenciones a los costes de inversión están diseñadas para hacer que los vehículos eléctricos sean más atractivos económicamente y asequibles para los consumidores, promoviendo la adopción de coches eléctricos. Sin embargo, es importante tener en cuenta que estas subvenciones también podrían significar que los fondos no están disponibles para otros proyectos."
    label_text = "Este atributo describe si el gobierno tiene previsto introducir una <b>etiqueta climática voluntaria u obligatoria para los coches</b>. La etiqueta climática proporciona información sobre la <b>huella climática de los vehículos eléctricos en comparación con los vehículos de gasolina</b> y viceversa (es decir, cuántas menos emisiones produce un coche eléctrico). Una etiqueta climática es una herramienta política para mejorar la sensibilización y la transparencia de los consumidores respecto al impacto medioambiental de las elecciones de vehículos."
    adopters_policy_text = "Para evaluar el impacto potencial de un paquete de medidas, es importante conocer el número de personas afectadas por la medida. Este atributo indica el <b>porcentaje de vehículos eléctricos entre las nuevas matriculaciones <i>en el último año</i></b>. Por favor, toma tus decisiones basándote en el supuesto de que de todas las nuevas matriculaciones en tu región, un número especificado de personas ha comprado un vehículo eléctrico."
    policy_intro_text4 = "Las distintas partes de los paquetes de políticas estarán ocultas detrás de recuadros. Para ver la información, pasa el puntero del ratón por encima del recuadro. El recuadro se abrirá, permitiéndote ver la información."
    policy_intro_text5 = "Por favor, decida si apoyaría o no cada paquete político presentado."
    # TaskPage
    block_text_intro = "Por favor, ten en cuenta lo siguiente:"
    no_policies = "Las anteriores políticas del gobierno ya no están en vigor."
    product_intro_short = "En las siguientes páginas, te pedimos de nuevo que te decidas a favor o en contra de las ofertas de vehículos eléctricos. Como antes, ten en cuenta los siguientes atributos que varían entre las ofertas:"
    policy_change = "Ten en cuenta un cambio reciente en la política del gobierno:"

    policy_question = "¿Apoyarías este paquete de medidas políticas?"
    product_question = "¿Comprarías este vehículo eléctrico?"

    affirmative_text = "¡Felicidades por completar el bloque!"
    # Add block-specific texts
    policy_package_no = "Paquete de Políticas"
    product_offer_no = "Oferta Vehículo Eléctrico"

    BD1 = "Tenga en cuenta para las próximas ofertas de coches que el gobierno ha introducido una <b>etiqueta de huella climática del fabricante</b>. Esta etiqueta muestra cuántas emisiones de gases de efecto invernadero producen los coches y, en concreto, <b>cuántas emisiones ahorra un coche eléctrico en comparación con un coche de gasolina en %</b>. Puedes encontrar la etiqueta de cada vehículo eléctrico en el cuadro <b>Emisiones de gases de efecto invernadero durante el ciclo de vida</b>. <br><br>Además, el gobierno introdujo un <b>impuesto sobre las emisiones de la gasolina</b>. Este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel fijado por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o de unos Mex$ 5.5.</b>Esencialmente, conducir un vehículo de gasolina será más caro, lo que hará que los <b>vehículos eléctricos sean aún más rentables.</b> Para ver cuánto puedes ahorrar por cada 160 km si eliges un vehículo eléctrico, incluido el ahorro debido al precio del carbono, consulta el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br>"
    BD19 = "Tenga en cuenta para las próximas ofertas de coches que <b>todavía existe la etiqueta de huella climática del fabricante</b> que muestra <b>cuántas emisiones ahorra un coche eléctrico en comparación con un coche de gasolina en %</b>. Puede encontrar la etiqueta de cada vehículo eléctrico en la casilla <b>Emisiones de gases de efecto invernadero del ciclo de vida</b>. <br><br>No hay <b>impuesto sobre la gasolina para las próximas ofertas</b>. Esto significa que los vehículos eléctricos siguen siendo rentables en comparación con los coches de gasolina, pero el ahorro ya no se ve incrementado por un mayor precio de la gasolina.<br>"
    DB1 = "Por favor, tenga en cuenta para las próximas ofertas de automóviles que el gobierno introdujo una <b>etiqueta de huella climática del fabricante</b>. Esta etiqueta muestra cuántas emisiones de gases de efecto invernadero producen los automóviles y en particular <b>cuántas emisiones ahorra un coche eléctrico en comparación con un coche de gasolina en %</b>. Puede encontrar la etiqueta de cada vehículo eléctrico en el recuadro de <b>Emisiones de gases de efecto invernadero durante el ciclo de vida</b>. <br>"
    DB19 = "Tenga en cuenta para las próximas ofertas de coches que <b>además de la etiqueta de huella climática del fabricante</b> el gobierno introdujo un <b>impuesto sobre las emisiones de la gasolina</b>. Este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel establecido por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o alrededor de Mex$ 5.5. </b>Esencialmente, conducir un vehículo de gasolina será más caro, haciendo que los vehículos <b>eléctricos sean aún más rentables. </b> Para ver cuánto se puede ahorrar por 100 millas eligiendo un vehículo eléctrico, incluyendo el ahorro debido a la tarificación del carbono, consulte el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br><br>La etiqueta climática de cada vehículo se puede encontrar de nuevo en el cuadro <b>Emisiones de gases de efecto invernadero en el ciclo de vida</b>.<br>"
    AC1 = "Tenga en cuenta para las próximas ofertas de coches que el gobierno introdujo un <b>precio sobre las emisiones de la gasolina</b>. Este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel establecido por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o alrededor de Mex$ 5.5. </b>Esencialmente, conducir un vehículo de gasolina será más caro, haciendo que los <b>vehículos eléctricos sean aún más rentables.</b> Para ver cuánto puede ahorrar por cada 100 millas eligiendo un vehículo eléctrico, incluyendo el ahorro debido al precio del carbono, consulte el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br> "
    AC19 = "Tenga en cuenta para las próximas ofertas de coches que no hay <b>impuestos sobre la gasolina. Esto significa que los vehículos eléctricos siguen siendo rentables en comparación con los coches de gasolina, pero el ahorro ya no se incrementa por un mayor precio de la gasolina.<br>"
    CA1 = " "
    CA19 = "Tenga en cuenta para las próximas ofertas de coches que el gobierno introdujo un <b>precio sobre las emisiones de la gasolina</b>. Este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel establecido por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o de unos Mex$ 5.5. </b>Esencialmente, conducir un vehículo de gasolina será más caro, haciendo que los <b>vehículos eléctricos sean aún más rentables.</b> Para ver cuánto puede ahorrar por cada 100 millas eligiendo un vehículo eléctrico, incluyendo el ahorro debido al precio del carbono, consulte el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br>"
    BD37 = "Tenga en cuenta para las próximas ofertas de coches que el gobierno introdujo una <b>etiqueta de huella climática del fabricante</b>. Esta etiqueta muestra cuántas emisiones de gases de efecto invernadero producen los coches y, en concreto, <b>cuántas emisiones ahorra un coche eléctrico en comparación con un coche de gasolina en %</b>. Puedes encontrar la etiqueta de cada vehículo eléctrico en el cuadro <b>Emisiones de gases de efecto invernadero durante el ciclo de vida</b>. <br><br>Además, el Gobierno introdujo un <b>impuesto sobre las emisiones de la gasolina</b>. Como antes, este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel establecido por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o de unos Mex$ 5.5. </b>Esencialmente, conducir un vehículo de gasolina será más caro, haciendo que los <b>vehículos eléctricos sean aún más rentables.</b> Para ver cuánto puede ahorrar por cada 100 millas eligiendo un vehículo eléctrico, incluyendo el ahorro debido al precio del carbono, consulte el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br>"
    BD55 = "Tenga en cuenta para las próximas ofertas de coches que <b>todavía existe la etiqueta de huella climática del fabricante</b> que muestra <b>cuántas emisiones ahorra un coche eléctrico en comparación con un coche de gasolina en %</b>. Puede encontrar la etiqueta de cada vehículo eléctrico en la casilla <b>Emisiones de gases de efecto invernadero del ciclo de vida</b>. <br><br>No hay <b>impuesto sobre la gasolina para las próximas ofertas</b>. Esto significa que los vehículos eléctricos siguen siendo rentables en comparación con los coches de gasolina, pero el ahorro ya no se ve incrementado por un mayor precio de la gasolina.<br>"
    DB37 = "Tenga en cuenta para las próximas ofertas de coches que el gobierno introdujo una <b>etiqueta de huella climática del fabricante</b>. Esta etiqueta muestra cuántas emisiones de gases de efecto invernadero producen los coches y, en concreto, <b>cuántas emisiones ahorra un coche eléctrico en comparación con un coche de gasolina en %</b>. Puedes encontrar la etiqueta de cada vehículo eléctrico en la casilla <b>Emisiones de gases de efecto invernadero durante el ciclo de vida</b>. <br><br>"
    DB55 = "Tenga en cuenta para las próximas ofertas de coches que <b>además de la etiqueta de huella climática del fabricante</b> el gobierno introdujo un <b>impuesto sobre las emisiones de la gasolina</b>. Este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel establecido por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o alrededor de Mex$ 5.5. </b>Esencialmente, conducir un vehículo de gasolina será más caro, haciendo que los vehículos <b>eléctricos sean aún más rentables. </b> Para ver cuánto se puede ahorrar por 100 millas eligiendo un vehículo eléctrico, incluyendo el ahorro debido a la tarificación del carbono, consulte el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br><br>La etiqueta climática de cada vehículo se puede encontrar de nuevo en el cuadro <b>Emisiones de gases de efecto invernadero en el ciclo de vida</b>.<br>"
    AC37 = "Tenga en cuenta para las próximas ofertas de coches que ya no hay <b>etiqueta de huella climática del fabricante</b>. Pero el gobierno introdujo un <b>precio sobre las emisiones de la gasolina</b>. Este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel establecido por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o alrededor de Mex$ 5.5.</b>Esencialmente, conducir un vehículo de gasolina será más caro, haciendo que los <b>vehículos eléctricos sean aún más rentables.</b> Para ver cuánto puede ahorrar por cada 100 millas eligiendo un vehículo eléctrico, incluyendo el ahorro debido al precio del carbono, consulte el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br>"
    AC55 = "Por favor, tenga en cuenta para las próximas ofertas de coches que ya no hay <b>etiqueta de huella climática del fabricante ni impuesto sobre la gasolina</b><br>"
    CA37 = "Por favor, tenga en cuenta para las próximas ofertas de coches que ya no hay <b>etiqueta de huella climática del fabricante</b>.<br>"
    CA55 = "Tenga en cuenta para las próximas ofertas de coches que todavía <b>no hay etiqueta de huella climática del fabricante</b>. Pero el gobierno introdujo un <b>impuesto sobre las emisiones de la gasolina</b>. Este impuesto significa que el precio por litro de gasolina aumentará. Dependiendo del nivel establecido por el gobierno, este aumento podría ser de <b>alrededor de Mex$ 1.5 por litro o alrededor de Mex$ 5.5.</b>Esencialmente, conducir un vehículo de gasolina será más caro, haciendo que los <b>vehículos eléctricos sean aún más rentables.</b> Para ver cuánto puede ahorrar por cada 100 millas eligiendo un vehículo eléctrico, incluyendo el ahorro debido al precio del carbono, consulte el cuadro <b>Ahorro en comparación con un coche de gasolina</b>.<br>"
