class Lexicon:
    information_title = 'Información acerca de este estudio'
    instructions = "Instrucciones"
    no = "No"
    yes = "Sí"
    start = " Iniciar "
    stop = "Parar"
    your_decision = "Tu decisión"
    mobile_check = "Por favor, haz clic en siguiente"
    mobile = "Lo sentimos, este experimento no permite navegadores móviles. Por favor, vuelve al sitio web de Prolific y pega este código: "
    next = "Siguiente"
    consent_p1 = 'Gracias por tu interés por participar en este estudio. <br><br> Este estudio está supervisado por la MSc Anne Günther y el Prof. Ulf J.J. Hahnel, Facultad de Psicología, Universidad de Basilea, Suiza.'
    consent_p2 = ' Si aceptas participar en este estudio, se te pedirá que hagas lo siguiente:'
    consent_bullet1 = 'Comunicar algunos datos demográficos, como por ejemplo tu edad, sexo e ingresos.'
    consent_bullet2 = 'Completa una serie de cuestionarios. Se te preguntará por tus actitudes y perspectivas sobre distintos temas.'
    consent_bullet3 = 'Completarás una tarea experimental con múltiples rondas de elecciones hipotéticas de productos y políticas.'
    duration = 'Duración: '
    consent_p3 = 'Participar en este estudio requerirá aproximadamente <b>20-25 minutos</b> de tu tiempo.'
    risks = 'Riesgos y beneficios: '
    consent_p4 = 'No existen riesgos conocidos asociados a tu participación en esta investigación más allá de los de la vida cotidiana. Prolific te pagará por participar en este estudio. Tu participación podría ayudar a comprender mejor cuestiones de investigación abiertas en psicología conductual y ambiental.'
    privacy = 'Protección de datos y anonimato:'
    consent_p5 = ' La confidencialidad del registro de tus datos se mantendrá estrictamente mediante la asignación de códigos de identificación a cada participante, de modo que los datos nunca se vinculen directamente a la identidad individual. Nadie, incluidos los investigadores de este estudio, podrá revelar tu identidad. Los datos estarán disponibles de forma anonimizada en plataformas de Ciencia Abierta. Toda la información sensible que pudiera utilizarse para revelar tu identidad (incluido tu código de participante anónimo) se eliminará del conjunto de datos antes de publicarlos. Tampoco conoceremos nunca la identidad de ninguno de los participantes.'
    consent_p6 = ' La participación en este estudio es voluntaria. Puedes negarte a participar o retirarte en cualquier momento sin penalización. '
    consent_p7 = 'Sólo recibirás un pago por participar si completas el estudio hasta el final.  '
    consent_p8 = ' Si hay algo sobre el estudio o tu participación que no te quede claro, si tienes preguntas o deseas informar de un problema relacionado con la investigación, puedes ponerte en contacto con: Anne Günther en anne.guenther@unibas.ch o dejar un comentario al final de la encuesta.'
    consent_p9 = 'Al continuar con el estudio expresas tu consentimiento para participar en este estudio e indicas que'
    consent_bullet4 = 'tienes al menos 18 años'
    consent_bullet5 = 'has leído y entendido las condiciones establecidas y que has tenido tiempo suficiente para tomar una decisión.'
    consent_p10 = 'Si deseas participar, debes marcar las casillas que aparecen a continuación y hacer clic en siguiente. <b>Si no deseas participar, simplemente cierra esta ventana.</b> </p> <p> Basándome en la información presentada anteriormente, confirmo que deseo participar en este estudio y autorizo:'
    data_consent1 = 'El uso de los datos con fines científicos y la publicación de los resultados del estudio en revistas o libros científicos, dado que los datos serán anónimos y no se revelará ninguna información sobre mi identidad.'
    data_consent2 = 'El uso de los datos con fines docentes (cursos y conferencias para estudiantes y profesionales que estén sujetos al secreto profesional).'